{{- if .Values.rmq.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert
  labels:
    app: ca-cert
type: Opaque
data:
  encoded.pem: {{  required "encodedPem not found. Please use '--set secrets.encodedPem=/path/to/encoded.pem'" .Values.secrets.encodedPem | b64enc }}
{{- end }}