apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp-node-{{ .Values.clusterName  }}-policy-pvc
spec:
  accessModes:
    - ReadWriteOnce        # Can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi         # Request 1 GB of storage
