{{- if .Values.rmq.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-tls
  labels:
    app: {{ .Values.rmq.name }}
type: Opaque
data:
  ca_certificate.pem: {{  required "ca_certificate not found. Please use '--set secrets.rmq.ca_certificate=/path/to/ca_certificate.pem'" .Values.secrets.rmq.ca_certificate | b64enc }}
  certificate.pem: {{  required "server certificate not found. Please use '--set secrets.rmq.certificate=/path/to/certificate.pem'" .Values.secrets.rmq.certificate | b64enc }}
  key.pem: {{  required "key not found. Please use '--set secrets.rmq.key=/path/to/key.pem'" .Values.secrets.rmq.key | b64enc }}
{{- end }}