apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
  labels:
    app: {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
  labels:
    app: {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - '*'
  resources:
  - deployments
  - pods
  - secrets
  - tokenreviews
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
  labels:
    app: {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
subjects:
- kind: ServiceAccount
  name: {{ include "prefixWithVariable" (dict "prefix" .Values.cpNode.serviceAccountName "variable" .Values.clusterName ) | quote }}
  namespace: '{{ .Release.Namespace }}'